version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:18.12.0
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd Docker
            make install
      - run:
          name: run lint
          command: |
            cd Docker
            make lint
workflows:
  default:
    jobs:
      - build